### ISSUE TITLE
com.tuya.smart.uispecs  AAPT: error:duplicate value for resource 'attr/text' with config ''

### ISSUE THREAD

**Issue by lowly360** [TuyaInc/tuyasmart_panel_android_sdk#1]
尝试接入项目中（项目已对接TuyaSmartSdk) ，运行的时候报以下错误：
```
/Users/lelight/.gradle/caches/transforms-2/files-2.1/9900fd99d85108ba939914e101a099f6/jetified-tuyasmart-uispecs-0.0.3/res/values/values.xml:98:5-102:36: 
AAPT: error: duplicate value for resource 'attr/text' with config ''.
```
values的xml对应内容为：
```
 <declare-styleable name="LoadingButton"><attr format="string" name="text"/><attr format="color" name="textColor"/><attr format="color" name="textDisableColor"/><attr format="reference" name="normalDrawable"/><attr format="reference" name="loadingDrawable"/><attr format="reference" name="disableDrawable"/><attr format="enum" name="state">
            <enum name="normal" value="0"/>
            <enum name="loading" value="1"/>
            <enum name="disable" value="2"/>
        </attr></declare-styleable>
```

初步怀疑，资源LoadingButton与项目某第三方一资源重复了，因为是aar的原因改不了，无法运行下一步，需要你们帮助，能否给依赖包的资源都添加前缀，防止资源重复

**Comment by Thewhitelight** [comment]
implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.4' 你新增这个依赖，应该就可以解决。

**Comment by lowly360** [comment]
> implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.4' 你新增这个依赖，应该就可以解决。

解决了，THX

**Comment by Lelight-Iot** [comment]
> implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.4' 你新增这个依赖，应该就可以解决。

更新到0.5之后，添加这个依赖没用了，还是报同样的错误

**Comment by Thewhitelight** [comment]
抱歉 您的这个比较特殊
implementation("com.tuya.smart:panel-sdk:0.5.0", {
            exclude group: 'com.tuya.smart', module: 'tuyasmart-uispecs'
        })
implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.6'
@Lelight-Iot

**Comment by Lelight-Iot** [comment]
> 抱歉 您的这个比较特殊
> implementation("com.tuya.smart:panel-sdk:0.5.0", {
> exclude group: 'com.tuya.smart', module: 'tuyasmart-uispecs'
> })
> implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.6'
> @Lelight-Iot

还是不行，我怀疑我项目里面有同样得资源，但是涉及依赖太多了，不好一一排除
````
16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\2e68368d4576d3bda07a002954a6aaed\res\values\values.xml:100:5-104:36: AAPT: error: duplicate value for resource 'attr/text' with config ''.
16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]     
16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\2e68368d4576d3bda07a002954a6aaed\res\values\values.xml:100:5-104:36: AAPT: error: resource previously defined here.
16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]     
16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] ...\merged.dir\values\values.xml: error: file failed to compile.

**Comment by Thewhitelight** [comment]
--stacktrace

> > 抱歉 您的这个比较特殊
> > implementation("com.tuya.smart:panel-sdk:0.5.0", {
> > exclude group: 'com.tuya.smart', module: 'tuyasmart-uispecs'
> > })
> > implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.6'
> > @Lelight-Iot
> 
> 还是不行，我怀疑我项目里面有同样得资源，但是涉及依赖太多了，不好一一排除
> 
> ```
> 16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\2e68368d4576d3bda07a002954a6aaed\res\values\values.xml:100:5-104:36: AAPT: error: duplicate value for resource 'attr/text' with config ''.
> 16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]     
> 16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\2e68368d4576d3bda07a002954a6aaed\res\values\values.xml:100:5-104:36: AAPT: error: resource previously defined here.
> 16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]     
> 16:32:06.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] ...\merged.dir\values\values.xml: error: file failed to compile.
> ```

你用 ./gradlew build --stacktrace 看下是哪里的冲突

**Comment by Lelight-Iot** [comment]
试了 gradlew build --stacktrace 还是看不出什么问题

能否释放 com.tuya.smart:tuyasmart-uispecs:0.0.6 这个包内容给我修改一下

**Comment by Thewhitelight** [comment]
@Lelight-Iot 替换为 implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.7-L' 试试应该是可以了
> 试了 gradlew build --stacktrace 还是看不出什么问题
> 
> 能否释放 com.tuya.smart:tuyasmart-uispecs:0.0.6 这个包内容给我修改一下

**Comment by Lelight-Iot** [comment]
> @Lelight-Iot 替换为 implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.7-L' 试试应该是可以了
> 
> > 试了 gradlew build --stacktrace 还是看不出什么问题
> > 能否释放 com.tuya.smart:tuyasmart-uispecs:0.0.6 这个包内容给我修改一下

@Thewhitelight 大兄弟你好，能不能改一个0.0.9-L的给我（上次的0.0.7-L正常），我这边随着更新panel的版本和接入更多业务包，发现需要保持最新的才行

**Comment by nielev** [comment]
0.0.9-L已发布

**Comment by Lelight-Iot** [comment]
@Thewhitelight 更新到新的版本（com.tuya.smart:tuyasmart-bizbundle-panel:3.22.0-11）又不行，这个没法一直让你们改 LoadingButton，LoadingImageView 这种名字太容易重复了，你们可以考虑换一下吗，譬如加个前缀还是怎样的，或者有什么其它方式可以指导下吗
